### ISSUE TITLE
Plan for patient Merging

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/ehb-service#15]
We need to analyze a way to come up with a unified merge process. We may not have a huge use case yet, but lets start thinking.  

First thought:

Examples:
- Merge Patient 2 to Patient 1 on two different protocols.
- Merge Patient 2 to Patient 1 on the same protocol.

@alexanderkgonzalez @seg1129

**Comment by alexfelmeister** [comment]
@alexanderkgonzalez please write out your manual steps here after you've done a few.

**Comment by seg1129** [comment]
@alexanderkgonzalez to be included in completing this project
