### ISSUE TITLE
eHB/Proband Pedigree Integration requirements

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/ehb-service#23]
Add relationship types to Relation table with type Familial. Add new table: 

class PedigreeRelation(CreatedModified):
    subject = models.ForeignKey(Subject)
    relation = models.CharField(max_length=50)
    related_subject = models.ForeignKey(Subject)

see commit f805328c232b8d0ef9f52eea1bae0bb90a257290

**Comment by alexfelmeister** [comment]
Phase 1

Functional
- Relating two subjects
    - description of their relationship
    - BRP will do Relationship Selection based on current subject in a protocol
    - BRP Shows relationship after it’s made
    - BRP will display possible relationships from proband
        - MRNed  
       

Non Functional 
    - Store it in eHB 
    - eHB will not require protocol context in relationship storage
    - eHB protocol context of a subject drives how the BRP will manage the relationship
    - Proband Data Lookup

Phase 2

Functional
- User shown {proband data} for a given MRN.
    - {proband data: 


Non Functional
    - Validation of Relationship
    - 

Phase 3

Functional
- Virtualization 

Non-Functional
- Graph Storage




Ahnentafel

**Comment by alexfelmeister** [comment]
@penningtonj See above. This issue is now referred to as Proband/eHB Integration Project and requirements are based on that concept.

**Comment by seg1129** [comment]
[BRP Proband integration.pdf](https://github.com/chop-dbhi/ehb-service/files/1975671/BRP.Proband.integration.pdf)

**Comment by seg1129** [comment]
new updated table structure for relationships:
     Subject: foreign Key to subjects
     Related subject: foreign Key to subjects
     Subject role: foreign key to relation table
     Related subject role: foreign key to Relation table
     protocol: protocol PK#

**Comment by seg1129** [comment]
Non-Functional requirements for the EHB-Service:
a.	add the following functions to the API
      i.	Add a relationship
     ii.	Get relationships for a given subject in a protocol
     iii.	Get relationships for a given protocol
     iv.	Modify a relationship
     v.	Remove a relationship
b.	Create unit tests for all API calls

For full requirements: 
[Proband_BRPToolkit integration P1 Design document.docx](https://github.com/chop-dbhi/ehb-service/files/2267050/Proband_BRPToolkit.integration.P1.Design.document.docx)
