### ISSUE TITLE
Define requirements for eHB tech refresh

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/ehb-service#39]

**Comment by szh2425** [comment]
[eHB Service Tech Refresh SOW.docx](https://github.com/chop-dbhi/ehb-service/files/2245683/eHB.Service.Tech.Refresh.SOW.docx)

**Comment by szh2425** [comment]
edited SOW based on templates; ready for review: 
[eHB Tech Refresh SOW draft v1.docx](https://github.com/chop-dbhi/ehb-service/files/2250836/eHB.Tech.Refresh.SOW.draft.v1.docx)
