### ISSUE TITLE
Admin: No subject group object access 

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/ehb-service#7]
Subject group object access via django admin interface could cause major issues with one small click. This should either be not accessible or not savable.

**Comment by alexfelmeister** [comment]
@seg1129 reopened @alexanderkgonzalez if you have any diagrams. Let's start to look at them.

**Comment by seg1129** [comment]
https://github.com/chop-dbhi/ehb-service/pull/17/commits/d9b725db29a2a56e675cc3cac10908b76db83978 #17
