### ISSUE TITLE
Replace restlib2 with Django rest framework

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/ehb-service#70]

**Comment by szh2425** [comment]
Update: 
Currently working on this -> (estimate will take about 2 weeks to complete) 
Have refactored GET, and PUT of  resource.Subject to using DjangoRestFramework. 
Will need to refactor the rest of the files in resources like Groups, Organization, etc.

**Comment by szh2425** [comment]
Notes for changing from Restlib2 to DjangoRestFramework (DRF) can be viewed here: 
https://docs.google.com/spreadsheets/d/1F5IBzvZBCZQadXyV3DFYA1s4gW_YosvvWB7rtH_0tM/edit#gid=0

**Major changes include:**

- Default response renderer and parser is set to json
- The names of the classes under resources folder in ehb/api was changed to 'views'. The folder was also renamed to views
- added as_view to all the url patterns
- DRF requires a Response or HTTPResponse object to be returned for all api calls so changed from returning json.dumps to Response object

**Instructions for updating to use DRF**

1. Pip list -> make sure you are in django1.11. If not, follow instructions in other issues to upgrade to django1.11
2. Pip install -r requirements.txt
3. Pip list  -> make sure that djangorestframework was installed 
4. Run tests with: Python bin/manage.py test core api
