### ISSUE TITLE
EHB Encryption/Decryption Question

### ISSUE THREAD

**Issue by szh2425** [chop-dbhi/ehb-service#86]
**Would anyone be able to verify that the following is true?**

**My understanding of EHB encryption/decryption in Python2:**
_Encryption_
1. We get value from fixtures as string: **ex. ‘John’**
2. We encode to bytes: **ex. b’John';** `(get_db_prep_value() in encryptionFields.py)`
3. We encrypt via pycrypto aes: **ex. x00@1-j{3(}4i]** `(encrypt() in encryptionServices.py)`
4. We convert encryption into hexstring: **ex. ‘d8b774de4d15d8**’ `(get_db_prep_value() in encryptionFields.py)`

_Decryption_
1. We get value from database as hex string: **ex.  ‘d8b774de4d15d8’** `(from_db_value () in encryptionFields.py)`
2. We unhexify the hex string: **ex.  x00@1-j{3(}4i]**  `(to_python() in encryptionFields.py)`
3. We decrypt via pycrypto: **ex. b'John'** (decrypt () in encryptionServices.py)`
4. We decode to string: **ex. ‘John’**  `(to_python() in encryptionFields.py)`

 **What I think needs to occur for EHB encryption/decryption in Python3** 
_Encryption_
1. We get value from fixtures as string: **ex. ‘John’**
2. We encode to bytes, **ex. b’John’;** 
3. We encrypt via pycryptodome aes, **ex. b'\xd8\xb7t\xdeM\x15\**
4. We convert encryption into hex, which is bytes, **ex. b'd8b774de4d15d8**
5. ***** We decode hexabytes to string: **ex.  ‘d8b774de4d15d8’** 

_Decryption_
1. We get value from database as hex string: **ex.  ‘d8b774de4d15d8’**
2. ****We encode that to bytes: **ex. b‘d8b774de4d15d8’**
3. We unhexify **ex. b'\xd8\xb7t\xdeM\x15\**
4. We decrypt via pycryptodome aes, **ex. b’John’**
5. We decode to string, **ex. ‘John’**

Issues: EncryptionFields.py is confusing because there's a BaseClass that inherits EncryptCharField and EncryptDateField. The methods: to_python and get_db_prep_value appear in both the Base and child classes, and it becomes unclear which method is being used for the unhexify/hexify, encrypt/decrypt.

**Comment by seg1129** [comment]
To determine which method gets called (from child class or base class) we have to look at how it is being called. For python, if the child function is overriding a parent function, the child function will be used unless the parent function is explicitly called. To see where the encryption functions are being called we can see that in this file: https://github.com/chop-dbhi/ehb-service/blob/master/ehb_service/apps/core/models/identities.py

looking through this file, I don't see it explicitly calling the parent functions, so if the function is overridden in the child class, that is what is called.

Does this help?
