### ISSUE TITLE
Upgrade to supported version of Django

### ISSUE THREAD

**Issue by tjrivera** [chop-dbhi/ehb-service#9]
This project currently depends on Django 1.5. We should probably target 1.11 (LTS)

**Comment by seg1129** [comment]
for each upgrade this is my process - please provide any suggestions

**In local dev**
- creating new virtual env
- reviewing Django version notes
- making adjustments to EHB code based on Django version notes and components that are depreciated. 
- running unit test with command: python -Wall ./bin/manage.py test api core ('-Wall' to view depreciation components)
- if depreciation warnings are identified modify code to fix and run unit test command again to verify problem was solved. 
- push code to dev when ready

**regression & user acceptance testing**
- have a version with new code, and connected to BRP with production data in dev server for team QA. 
- Test EHB admin functionality
- have EIG team run ETL against QA BRP/EHB 
- validate BRP can update EHB
- Validate BRP can update

**Production Migration**
- create PGdump of EHB and BRP Database
- pull request to bring code to production
- if error: 
     - undo latest commit and validate Jenkins build and deploy
     - pgresore EHB and BRP databases

**Comment by tjrivera** [comment]
@seg1129 This process seems reasonable to me. I don't have any further recommendations!

**Comment by seg1129** [comment]
@tjrivera is there any update on when we will get more space on the dev server?

**Comment by tjrivera** [comment]
@seg1129 no update from research IS on this yet. FYI we may want to keep CHOP specific request tracking outside of this repo since it is a public forum. Open to suggestions.
