### ISSUE TITLE
Circle CI testing has been failing for a year

### ISSUE THREAD

**Issue by fiendish** [chop-dbhi/ehb-service#98]
Circle integration should either be fixed or removed. Failing tests either matters or doesn't. If it matters, then the tests should be passing. If it doesn't, then why bother running the tests at all?

**Comment by seg1129** [comment]
Hello! All tests are passing, they are extremely important to make sure we are maintaining the functionality and stability of this application. Circle integration is not working, I'll remove it from the repo.
